title: Luminescence dating for objects from collection
author: Antoine J.C. Zink
email: antoine.zink@culture.gouv.fr
description: > # this means to ignore newlines until "baseurl:"
  Bayesian approach and metrology of luminescence dating.

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# social links
github_username:  Zink-Antoine

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
